### ISSUE TITLE
Support `--start-from-head` option

### ISSUE THREAD

**Issue by vlcinsky** [jorgebastida/awslogs#27]
Allow getting just the latest log events by supporting `--start-from-head` option. By default (without that option), we would start getting only very latest log records ("tailing")

This is not so simple as it sounds (conflicting options, multiple scenarios...)

Implementation
=============

Using missing `startFromHead` parameter in `filter_log_events`
----------------------------------------------------------------------------------------

[CloudWatchLogs.Client.get_log_events](http://boto3.readthedocs.org/en/latest/reference/services/logs.html#CloudWatchLogs.Client.get_log_events) supports parameter `startFromHead`

Unfortunately, [in code](https://github.com/jorgebastida/awslogs/blob/master/awslogs/core.py#L140) we use [CloudWatchLogs.Client.get_log_events](http://boto3.readthedocs.org/en/latest/reference/services/logs.html#CloudWatchLogs.Client.get_log_events) which does not support such option.

I would propose to keep using `get_log_events` method and use `startTime` with current time

Client having not synced clock
-------------------------------------------
Using current time can fail, if use would have bad time synchronization (being ahead of time would cause long period of silence).

Options are:

- ignore such scenario, declare time being properly synced as prerequisite
- get current time from some "live" request to AWS
- make one initial call to `get_log_events` with `startFromHead` being `False` and use timestamp from latest record as time for our `--start`. (did not test it if it returns any record at all if there is no new record added at that moment).
- after we do the call to `filter_log_events`, get the current time from HTTP headers of that request (I am not aware of simple method to do so) and if it would differ more than 30 seconds from current one, print warning to stderr and continue.

Ignoring seems fine to me.

Conflicting `--start` and `--start-from-head` options
-----------------------------------------------------------------------
These two options are mutually exclusive. In case they are both set by user, we have following options:

- use `--start` and ignore `--start-from-head`, possibly printing some warning to stderr
- reject such combination of options and exit

Exiting seems better to me (we will force user to think, what he really wants to get).

`--start-from-head` being off by default
-------------------------------------------------------
When there is no `--start` value, `awslogs` shall start from tail of log. This seems to me intuitive behaviour (user wanting to see, what is happening just now). This fits very well with `--watch`, where in many cases large logs would take too long time to show current records, which user probably cares about.

PS: Did I tell you I like the tool a lot?

**Comment by jorgebastida** [comment]
Thank you very much for this very detailed description!

Yes, we use ``filter_log_events`` (http://boto3.readthedocs.org/en/latest/reference/services/logs.html#CloudWatchLogs.Client.filter_log_events) because that's the only way to get events merged from several streams - which is really convenient.

It perhaps sounds like a workaround, but the way I use solve what you are trying... is to set a really low start time like... ``-s5s`` or ``-s5m`` which (at least for me) is fine. In the other hand doing extra work to get the "real" head sounds like a lot of effort, when something like ``-s5s`` sounds like a good-enough-approximation. 

This opens the question of why I did choose (quite arbitrarily) ``24h`` as the default ``--start`` time (https://github.com/jorgebastida/awslogs/blob/master/awslogs/bin.py#L51) which right looks sounds pretty much wrong.

What do you think about if we make the default ``--start`` time be ``3m``?

**Comment by jorgebastida** [comment]
After giving this a think, I've decided that the 24h default value I pick was rather stupid.... I've make it be 5 minutes.

**Comment by vlcinsky** [comment]
I was not aware of the possibility to specify --start option with other than RFC 3339 format.

I like it, The "start 1 minute ago" by `-s1m` is really nice.
The default `-s3m` sounds very good.

Question: what formats are supported for `--start` and `--end`?

Trying to use `-s30s` did not work for me well, expecting -30 seconds, getting all records since today midnight + 30s.
